package: yform_field
version: '1.0'
author: 'Alexander Walther'
supportpage: https://github.com/alexplusde/yform_field

requires:
    redaxo: ^5.8.1
    yform: '^4'
    php:
        version: ^7.4

page:
    hidden: true
