package: yform_field
version: '2.3.0'
author: 'Alexander Walther'
supportpage: https://github.com/alexplusde/yform_field

requires:
    redaxo: ^5.15
    yform: '^4.1'
    media_manager: '2.12.1'
    php:
        version: ">=8.1,<9"
        extensions: [intl]


page:
    hidden: true

pages:
    yform/yform_field_docs:
        title: 'Zusätzliche Felder'
        subPath: README.md
        icon: rex-icon fa-info-circle
        itemclass: pull-right
        perm: yform_field[]
